name: Zadanie Moroz
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sprawdzanie repo
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pusz na doker
        uses: docker/build-push-action@v2.6.0
        with:
            context: .
            file: Dockerfile
            push: true
            repository: 6e3nohtobui/zadanie1
            tags: latest
